# Generated by Django 6.0 on 2025-12-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('soat_fecha', models.DateField(blank=True, null=True)),
                ('tecnomecanica_fecha', models.DateField(blank=True, null=True)),
                ('poliza_fecha', models.DateField(blank=True, null=True)),
                ('extrajudicial_fecha', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
