# Generated by Django 6.0 on 2025-12-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=10)),
                ('licencia_vencimiento', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
