# Generated by Django 6.0 on 2025-12-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0002_conductor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
