# Generated by Django 6.0 on 2025-12-08 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0003_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FUEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ruta', models.CharField(max_length=200)),
                ('objeto_contrato', models.CharField(default='Transporte Especial de Pasajeros', max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_vehiculos.cliente')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_vehiculos.conductor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_vehiculos.vehiculo')),
            ],
        ),
    ]
