# Generated by Django 6.0 on 2025-12-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0004_fuec'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='licencia_archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/licencias/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='poliza_archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/polizas/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='soat_archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/soat/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tecnomecanica_archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/tecnomecanica/'),
        ),
    ]
