# Generated by Django 6.0 on 2025-12-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0007_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='fecha_asignacion',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha',
            field=models.DateField(null=True, blank=True),
        ),
    ]

